/**
 * @file rodscriteriawidget.h
 * @brief Definition of RodsCriteriaWidget class
 *
 * The RodsCriteriaWidget class extends the Qt widget class QWidget and
 * implements an abstract widget for entering an iRODS GenQuery condition.
 *
 * Copyright (C) 2014-2015 University of Jyväskylä. All rights reserved.
 * License: The BSD 3-Clause License, see LICENSE file for details.
 *
 * @author Ilari Korhonen
 */

#ifndef RODSCRITERIAWIDGET_H
#define RODSCRITERIAWIDGET_H

// C++ standard library headers
#include <string>

// Qt framework headers
#include <QWidget>

// Kanki iRODS C++ class library headers
#include <rodsconnection.h>
#include <_rodsgenquery.h>


class RodsCriteriaWidget : public QWidget
{
    Q_OBJECT

public:

    //
    explicit RodsCriteriaWidget(QWidget *parent = 0);

    // pure virtual function to define interface to the evaluation
    // of the genquery conditions generated by the widget
    virtual void evaluateConds(Kanki::RodsGenQuery *query) = 0;

};

#endif // RODSCRITERIAWIDGET_H
